### ISSUE TITLE
Error in curl::curl_fetch_disk

### ISSUE THREAD

**Issue by Ryan-Roberts123** [giacfalk/blackmaRble#1]
Firstly, thanks to giacfalk for this library, it has been very useful. I'm not entirely sure this error is even a fault in your code or something else. If this post is in the wrong place I'm sorry, feel free to delete it.

I have found an obscure error, trying to download VNP46A2 data, over Kyiv Ukraine, on the 27th February. The same date works for other areas, and different dates work for Kyiv. Data does appear to be there in full via:

https://ladsweb.modaps.eosdis.nasa.gov/search/order/4/VNP46A2--5000/2022-02-27..2022-02-27/DB/Country:UKR

I have used essentially the same code to get data for ~50 days prior to the 27th Feb, which worked fine. Any help would be greatly appreciated. The code I am using and Error:

```
library(blackmaRble)
library(tidyverse)
library(sf)
library(osmdata)

# Creates a bounding box around Kyiv
bbx <- osmdata::getbb(
  "Kyiv, Ukraine", 
  format_out = "sf_polygon"
)

bbx <- st_as_sf(bbx$polygon$geometry[1])

bbx <- 
  spPolygons(extent(bbx),
             crs = crs(bbx))

bbx$ID = 1

# Place to save a shapefile
save_dir <- ""

writeOGR(obj = bbx, dsn = save_dir, 
         layer = "test_shp", driver = "ESRI Shapefile")

bm_initialize("username", "password")

output <- bm_get_data(
  date_start='2022-02-27', 
  date_end='2022-02-27', 
  delta='days', 
  data_product='VNP46A2', 
  variable_name="DNB_BRDF_Corrected_NTL", 
  custom_shape=save_dir
)
```

Request failed [ERROR]. Retrying in 2.1 seconds...
Error in curl::curl_fetch_disk(url, x$path, handle = handle): Error while processing content unencoding: incorrect data check

**Comment by giacfalk** [comment]
Dear Ryan,

First of all thanks for signalling this and sorry for the late reply. I don't know if you already solved the issue in some way.

The first thing that comes to my mind given what you say (i.e. that you only find the issue to occur over Kyiv) is that for military/security reasons NASA might have decided not to publish daily nighttime light data in zones affected by the Russian invasion war.

But, in the meantime, another user signalled that the server is often (but not always) replying with error 504 [gateway timeout], which of course does not depend from me. I am inquiring into this annoying occurance that was not taking place when I developed the package, but I am unsure if I can easily solve it... 

I will keep you posted and please let me know if you have developments, too.

Best,
Giacomo

**Comment by kketevani** [comment]
Hello Giacomo, 
I am facing a similar error. I have tried multiple locations but the error is still the same. 

Checking credentials..
Successfull login to earthdata 
[1] "Downloading file 1 of 4"
Error in curl::curl_fetch_disk(url, x$path, handle = handle): Failed to open file

any suggestions? thanks

**Comment by Ryan-Roberts123** [comment]
Hello kketevani, 
I've also had this when you already have files saved onto your desktop. Delete those files and retry it, it should work.
 
Thankyou Giacomo for the reply, I have begun to use the original data for my work. However this package was great for checking my ideas, so it's much appreciated. 
Thanks

**Comment by kketevani** [comment]
Thank you Ryan, it works perfectly now )) 
best,
